### ISSUE TITLE
Error fetching providers from terraform-registry

### ISSUE THREAD

**Issue by wanfuuyu** [kubevela/terraform-controller#317]
I use terraform-controller to deploy helm releases.

Everything goes fine in my dev env, but sometimes `terraform init` will stuck in fetching providers from terraform registry due to network issue

I see all volumes mounted in apply-job is emptyDir and mounted as a directory, a 'pre-init' images with all providers downloaded can not work as expected

Maybe there should be something like  "-plugin-dir"  from terraform init command

![image](https://user-images.githubusercontent.com/8027958/170933315-1610cf42-36cb-4f33-a8a1-cf39a91de3fb.png)

**Comment by wanfuuyu** [comment]
please take a look  @zzxwill

**Comment by wanfuuyu** [comment]
well, I use terraform helm provider in [cloud provider  custom](https://github.com/oam-dev/terraform-controller/blob/master/examples/custom/configuration_hcl_example.yaml)

Errors are reported by "terraform init", and will show only there is a network issue, **what I need is a way to run the apply job locally** and no need to fetch from the network

Maybe the issue title is confusing 😅

**Comment by zzxwill** [comment]
@wanfuuyu Then you need to build your custom provider in the Terraform image https://github.com/oam-dev/docker-terraform.
