### ISSUE TITLE
The execution of the terraformDestroy method fails and the application cannot be uninstalled

### ISSUE THREAD

**Issue by wujiuye** [kubevela/terraform-controller#363]
We often encounter situations where terraformApply fails to execute successfully due to various reasons, such as incorrect namespace installation for the app or the absence of a 'git ssh secret' in the namespace. In such cases, we may want to uninstall the app instead of adding a 'git ssh secret' to the same namespace in order to make terraformApply successful. However, we may not be able to uninstall the app either, because terraformDestroy also fails to execute.

I want to fix this issue, but I am not sure if it is a bug or a security consideration. 

For example, before executing the terraformDestroy method, we can check if the 'tfstate' file exists. If it does not exist, there is no need to execute the terraformDestroy method.

**Comment by wujiuye** [comment]
example ：`MountVolume.SetUp failed for volume "git-auth-configuration" : secret "gitlab-ssh-key-secret" not found`

**Comment by wujiuye** [comment]
Sorry, there is a problem with my description. The point is not to check whether the secret exists, but because the secret does not exist, the apply job cannot be successfully executed, and then I want to uninstall the application, the destroy job will definitely fail to execute, and finally I cannot uninstall the application.

**Comment by chivalryq** [comment]
@wujiuye Would you check the function `validateSecretAndConfigMap` which will check the secret `git-auth-configuration` before Job is applied. This is the first quesion. 

For other reasons if job is failed. I agree we check the state to decide to delete the Configuration quickly.

**Comment by wujiuye** [comment]
sure, validateSecretAndConfigMap will check whether the referenced git secret exists, but it does not verify whether the namespace is the same as the namespace of the Configuration. and the pod mount restricts the config or secret to be in the same namespace as the pod, otherwise it will mount failure.

So, My idea is:
1. I want to increase the verification of the namespace of the ConfigMap and Secret to be mounted.
2. The failure of terraformApply does not mean that it has never been successful, but if the 'tfstate' file does not exist, then there is no need for terraformDestroy, which can quickly clean up resources. don't know if there is a loophole in this idea.

**Comment by wujiuye** [comment]
Of course, I tried to implement these two idea. I then split the first idea into a new issue
